name: Continuous integration

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: docker build -t acelaya/blog:temp .
